### ISSUE TITLE
Broken with latest Sidekiq 7.1.4?

### ISSUE THREAD

**Issue by aarona** [sensortower/sidekiq-throttled#155]
`sidekiq: 7.1.4`
`sidekiq-throttled: 0.17.0`

Simply upgrading `sidekiq` from `6.5.5` to `7.1.4` (necessary because of a HIGH vulnerability found in `sidekiq`), I'm getting the following error when trying to run `rspec`:

```
Failure/Error: require File.expand_path('../config/environment', __dir__)

NoMethodError:
  undefined method `error_handlers' for Sidekiq:Module

          Sidekiq.error_handlers << Sidekiq.method(:default_error_handler)
                 ^^^^^^^^^^^^^^^
# ./config/application.rb:35:in `<top (required)>'
# ./config/environment.rb:4:in `require_relative'
# ./config/environment.rb:4:in `<top (required)>'
# ./spec/rails_helper.rb:13:in `require'
# ./spec/rails_helper.rb:13:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- sidekiq-throttled
#   ./config/application.rb:35:in `<top (required)>'
```

`./config/application.rb:35` is simply my `Bundle.require` statement:

```
Bundler.require(*Rails.groups, *Feature.groups)
```

Any ideas?

**Comment by aarona** [comment]
Ok, looks like upgrading to `1.0.0.alpha` fixed this issue for me. I wanted to avoid doing that in case it might have been buggy. I'll try the `1.0.0.alpha.1` after my rspec tests pass (they are now running).

Closing the ticket. Sorry for the confusion.
